### ISSUE TITLE
залупа на волоске

### ISSUE THREAD

**Issue by RomashkaTea** [SavokBS/VokeCore#5]
скачал моё ядро,добавил гкода с бсдс и ого! крутое "асюнк" ядро!!!!

**Comment by SavokBS** [comment]
ЭХ ГДЕ Я ПИСАЛ ЧТО ОНО КРУТОЕ

**Comment by SavokBS** [comment]
ЭХ ГДЕ ГКОД В БСДС ДУРА ТЫ КРАЗОР ПОЛУЧШЕ ТЕБЯ МОЖЕТ ЭХ 😢
